//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agro_webApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agro_appEntities : DbContext
    {
        public agro_appEntities()
            : base("name=agro_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datos_Usuario> datos_Usuario { get; set; }
        public virtual DbSet<finca> finca { get; set; }
        public virtual DbSet<lotes> lotes { get; set; }
        public virtual DbSet<tipo_Usuario> tipo_Usuario { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
