//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agro_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_Usuario
    {
        public int id_datos { get; set; }
        public int id_Usuario { get; set; }
        public string Nombre_completo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string pais { get; set; }
        public string profesion_oficio { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
