//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agro_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public finca()
        {
            this.lotes = new HashSet<lotes>();
        }
    
        public int id_Finca { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public string descripcion { get; set; }
        public string extension { get; set; }
        public int id_Usuario { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lotes> lotes { get; set; }
    }
}
