//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agro_webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotes
    {
        public int id_Lote { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string extension { get; set; }
        public int id_Finca { get; set; }
        public string prioridad { get; set; }
        public string descripcion { get; set; }
    
        public virtual finca finca { get; set; }
    }
}
